version: 3

tasks:
  dist:
    cmds:
      - mkdir -p ./dist
  syntaxck:
    env:
      GOARCH: wasm
      GOOS: js
    cmds:
      - go build -o ./dist/syntaxck.wasm ./wasm/syntaxck
      - wasm-opt ./dist/syntaxck.wasm --enable-bulk-memory -Oz -o ./dist/syntaxck.pack.wasm
      - cp ./dist/syntaxck.pack.wasm ./frontend/public/
    sources:
      - ./wasm/syntaxck/*.go
    generates:
      - ./dist/syntaxck.wasm
      - ./dist/syntaxck.pack.wasm
      - ./frontend/public/syntaxck.pack.wasm
