version: 3

tasks:
  dist:
    cmds:
      - mkdir -p ./dist
  wasm-exec:
    cmds:
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./frontend/src/wasm_exec.js
    generates:
      - ./frontend/src/wasm_exec.js
  syntaxck:
    env:
      GOARCH: wasm
      GOOS: js
    cmds:
      - go build -o ./dist/syntaxck.wasm ./wasm/syntaxck
      - wasm-opt ./dist/syntaxck.wasm --enable-bulk-memory -Oz -o ./dist/syntaxck.pack.wasm
      - mkdir -p ./frontend/src/assets/
      - cp ./dist/syntaxck.pack.wasm ./frontend/src/assets/syntaxck.pack.wasm
    sources:
      - ./wasm/syntaxck/*.go
    generates:
      - ./dist/syntaxck.wasm
      - ./dist/syntaxck.pack.wasm
      - ./frontend/src/assets/syntaxck.pack.wasm
